messages = {
    'pt-br': {
        'leave': 'Sair',
        'menu_title': 'Menu - Hotel Service',
        'sidebar_users': 'Usuários',
        'sidebar_residents': 'Hóspedes',
        'sidebar_services': 'Serviços',
        'sidebar_rooms': 'Quartos',
        'menu_new_user_msg': 'Aqui você pode cadastrar um novo usuario, este pode vir a ser um Hospede ou ADM',
        'menu_new_resident_msg': 'Aqui você pode ver todos os Hospedes registrados',
        'menu_new_service': 'Vizualize aqui os pedidos efetuados a cozinha',
        'menu_new_room': 'Vizualize os quartos e seus estados',
        'menu_checkin_msg': 'Aqui você pode fazer o Check-in de hóspedes já cadastrados',
        'menu_checkout_msg': 'Aqui você pode fazer o Check-out ao fim da estadia de um hóspede',
        'error_hos_saved': 'Hóspede criado com sucesso!',
        'error_emp_saved': 'Administrador criado com sucesso!',
        'error_select_type': 'Favor selecionar um tipo de funcionario!',
        'error_pwds': 'As senhas não estão iguais, favor tentar novamente!',
        'type': 'Tipo de Usuário',
        'select_type': 'Selecione o tipo de Usuário',
        'new_user': 'Cadastrar Usuário',
        'rooms_stab': 'Quartos do estabelecimento',
        'filters_room': 'Utilize os filtros para procurar por situações específicas',
        'filters_room_free': 'Quartos Livres',
        'filters_room_busy': 'Quartos Ocupados',
        'filters_room_no_filter': 'Sem Filtros',
        'filter': 'Filtrar',
        'rooms_number': 'Nº do Quarto',
        'floor': 'Andar',
        'daily': 'Diária',
        'change': 'Alterar',
        'registered_users': 'Usuários registrados',
        'filters_adm': 'Apenas Administradores',
        'filters_guests': 'Apenas Hóspedes'


    },
    'en': {
        'leave': 'Exit',
        'menu_title': 'Menu - Hotel Service',
        'sidebar_users': 'Users',
        'sidebar_residents': 'Guests',
        'sidebar_services': 'Services',
        'sidebar_rooms': 'Rooms',
        'menu_new_user_msg': 'Here you can registrate new users, they can be ADM or guests',
        'menu_new_resident_msg': 'here you can see the whole list of guests',
        'menu_new_service': 'View here the requests made to the kitchen',
        'menu_new_room': 'View here the rooms and their states',
        'menu_checkin_msg': 'Here you can check in already registered residents',
        'menu_checkout_msg': "Here you can check out at the end of a guest's stay",
        'error_hos_saved': 'Guest created with success!',
        'error_emp_saved': 'Administrator created with success!',
        'error_select_type': 'Please select a type of employee!',
        'error_pwds': 'Passwords not matching, please try again!',
        'type': 'Type of user',
        'select_type': 'Select the type of user',
        'new_user': 'Register new User',
        'rooms_stab': 'Rooms of the establishment',
        'filters_room': 'Use filters to search for specific situations',
        'filters_room_free': 'Free Rooms',
        'filters_room_busy': 'Busy Rooms',
        'filters_room_no_filter': 'No Filters',
        'filter': 'Filter',
        'rooms_number': 'Room Number',
        'floor': 'Floor',
        'daily': 'Daily Value',
        'change': 'Change',
        'registered_users': 'Registered Users',
        'filters_adm': 'Only ADM',
        'filters_guests': 'Only guests'
    }
}
